### ISSUE TITLE
chore: implement write logic

### ISSUE THREAD

**Issue by mnorbury** [cloudquery/plugin-sdk-java#85]
Implement the write logic for:

- [memdb](https://github.com/cloudquery/plugin-sdk-java/blob/fc92542cb402d1ac0241aa781847eb8f2d211f87/lib/src/main/java/io/cloudquery/memdb/MemDB.java#L67)
- [PluginServer](https://github.com/cloudquery/plugin-sdk-java/blob/fc92542cb402d1ac0241aa781847eb8[…]java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java)

**Comment by erezrokah** [comment]
Done via https://github.com/cloudquery/plugin-sdk-java/pull/93 I think. Re-open if that's not the case
